# Generated by Django 5.1.2 on 2024-11-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "encrypted_secret",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("last_reencryption_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
