# Generated by Django 5.1.3 on 2024-11-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "_plaintext_secret",
                    models.CharField(db_column="plaintext_secret", max_length=50),
                ),
                ("_plaintext_json", models.JSONField(db_column="plaintext_json")),
                ("binary_encrypted_secret", models.BinaryField(blank=True, null=True)),
                (
                    "binary_reencryption_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("b64_encrypted_secret", models.CharField(max_length=1000)),
                ("b64_reencryption_time", models.DateTimeField(blank=True, null=True)),
                ("json_with_encrypted_secret", models.JSONField()),
                ("json_reencryption_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
